import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const Project: NextPage = (props) => {
  const router = useRouter();
  const routerProps = router.query;
  return (
    <>
      <Head>
        <title>asd Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>{JSON.stringify(routerProps)}</main>
    </>
  );
};

export default Project;
