import type { NextPage } from "next";
import Head from "next/head";
import Heading from "../../src/components/common/Heading/heading.component";
import Link from "../../src/components/common/Link/link.component";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>asd Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Link href="/">Home</Link>
        <Heading>BLABLA</Heading>
      </main>
    </>
  );
};

export default Home;
