import { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";

import Link from "../src/components/common/Link/link.component";
import Heading from "../src/components/common/Heading/heading.component";
import { useRouter } from "next/router";
import { useContent } from "../src/contexts/content.context";
import { useTheme } from "next-themes";

const Home: NextPage = () => {
  const router = useRouter();
  const { theme, setTheme } = useTheme();

  return (
    <div className="dark:bg-gray-800">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Link href="/projects">Projects</Link>
        <Heading>Heading</Heading>
        <button onClick={() => setTheme(theme === "dark" ? "light" : "dark")}>
          toggle
        </button>
      </main>

      <footer>dsa</footer>
    </div>
  );
};

export default Home;
